mongo:
  database: "dev_bunkers_core"
  host: "127.0.0.1:27017"
  authentication:
    username: ""
    password: ""
trade:
  distance: 10
  expire-time: 30 # seconds
currency:
  items:
    nugget:
      name: "&6Nuggets"
      lore:
        - "&7Golden Nuggets"
    bars:
      name: "&6&lBars"
      lore:
        - "&7Golden Ingot"
    coins:
      name: "&eCoins"
      lore:
        - "&7Sunflower"