name: "bunkers-core"
main: org.minevale.bunkers.core.BunkersCore
version: ${git.commit.id.abbrev}
author: Manny
depend: [WorldEdit]
commands:
  trade:
    usage: "/trade <player>"
    description: "Trading used to exchange items for currency between players"
    permission: "bunkers.command.trade"
  debug:
    usage: "/debug balance"
    description: "Debug command for bunkers core"
    permission: "bunkers.core.admin"
  economy:
    usage: "/economy <balance|clear|give|remove> <player> [currency]"
    aliases: ["eco"]
    description: "Economy management for bunkers core"
    permission: "bunkers.core.admin"
  bunker:
    usage: "/bunker <create|join> [player]"
    description: "Bunker management for bunkers core"
    permission: "bunkers.core.admin"
  chat:
    usage: "/chat <lock|clear> <global|local>"
    description: "Chat management for bunkers core"
  setchat:
    usage: "/setchat <local|global>"
    description: "Sets the chat mode globally"